#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
DOTFILES=$(pwd)
STOW_FOLDERS="nvim,lf,lsd,tmux,zsh"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder -t $HOME
    stow $folder -t $HOME
done
popd